### ISSUE TITLE
Cmake root directory

### ISSUE THREAD

**Issue by Eliastoomme** [mhyrzt/Dlib-Android-Face-Landmark#2]
Hi, I know it's been long time since you uploaded this project, but by any chance, can you help me to solve this issue? 
I'm trying to implement your project on my android device. But for some reason, it's not building.

Error: 
      CMake Error at CMakeLists.txt:5 (add_subdirectory):
      The source directory

---------------------------------
I tried to change the paths and rebuild, still not working. 
Thank you.

**Comment by mhyrzt** [comment]
OMG HI :D
Sure!
make sure you cloned recursively and the dlib_android folder in app/src/main/cpp exists

**Comment by Eliastoomme** [comment]
I did clone it recursively, but the cpp folder was empty.
I tried to create a folder and name it dlib_android, a new error occurred.
Thank you for your time!

**Comment by mhyrzt** [comment]
hmmmm!

clone this and put it in `app/src/main/cpp`
```bash
git clone https://github.com/mhyrzt/dlib_android.git
```
it's just a bunch of header files and source code of `dlib` library
https://github.com/mhyrzt/dlib_android


or clone the project again with this command:
```
git clone --recursive https://github.com/mhyrzt/Dlib-Android-Face-Landmark.git
```

**Comment by Eliastoomme** [comment]
Yes! it works now, thank you so much for your time and for your fast reply. 
Happy coding =)

**Comment by mhyrzt** [comment]
YW :D
